name: Join as Collaborator - Share Your Experience
description: Submit your experience and automatically become a repository collaborator
title: "[Collaboration] Developer Experience with X-CLI"
labels: ["testimonial", "community"]

body:
  - type: markdown
    attributes:
      value: |
        # Join as Collaborator Through Your Experience
        
        Share your technical experience with X-CLI and **automatically become a repository collaborator** with professional benefits.
        
        **Professional Benefits You'll Receive:**
        - **Repository collaborator status** with triage permissions for pull requests and issues
        - **Permanent backlink** from our documentation site to your profile for SEO benefits
        - **GitHub profile enhancement** as a contributor to an active open-source CLI tool
        - **Technical skill development** through TypeScript, Node.js, and AI integration experience
        - **Professional networking** opportunities within the developer tooling community
        
        **Your submission will be:**
        - Automatically validated and published to our website within 10 minutes
        - Featured with full professional attribution and link to your profile
        - Used to generate your immediate collaboration invitation
        
        *All processing is automated - you'll receive repository access within minutes of submission.*

  - type: input
    id: name
    attributes:
      label: Your Name
      description: Professional name for attribution and collaboration invitation (First and Last name)
      placeholder: "Alex Chen"
    validations:
      required: true

  - type: input
    id: title
    attributes:
      label: Job Title
      description: Your current role or position for professional credibility
      placeholder: "Senior Software Engineer"
    validations:
      required: true

  - type: input
    id: company
    attributes:
      label: Company/Organization
      description: Your professional affiliation or current project for networking context
      placeholder: "TechCorp"
    validations:
      required: true

  - type: textarea
    id: quote
    attributes:
      label: Your Technical Experience with X-CLI
      description: |
        Describe how X-CLI improved your development workflow and productivity. Focus on specific technical benefits.
        
        **Strategic Guidelines:**
        - Highlight specific productivity gains or workflow improvements (aim for 2-3 sentences)
        - Mention integration with your existing development stack
        - Reference measurable outcomes (time savings, error reduction, efficiency)
        - Connect to broader themes like AI tooling evolution or open-source values
        
        **Professional Examples:**
        - "X-CLI eliminated context switching in my development workflow, saving approximately 2 hours daily..."
        - "The MCP integration architecture opened new possibilities for connecting AI assistance with my existing tools..."
        - "Contributing to X-CLI enhanced my understanding of AI tool integration and production TypeScript development..."
      placeholder: "X-CLI eliminated context switching in my development workflow. The AI assistance directly in my terminal improved my debugging accuracy and saved significant time daily."
    validations:
      required: true

  - type: input
    id: link
    attributes:
      label: Professional Profile URL
      description: |
        Your professional profile for backlink attribution and networking opportunities
        
        **Preferred Platforms:**
        - GitHub: https://github.com/username (recommended for developer networking)
        - LinkedIn: https://linkedin.com/in/username (professional networking)
        - Personal website/portfolio: https://yoursite.dev (showcase your work)
        - Dev.to: https://dev.to/username (technical writing platform)
        - Twitter/X: https://x.com/username (industry engagement)
      placeholder: "https://github.com/username"
    validations:
      required: true

  - type: dropdown
    id: tags
    attributes:
      label: Technical Focus Areas
      description: Select up to 3 areas that best represent your expertise and contribution potential
      multiple: true
      options:
        - productivity
        - ai-assistance
        - terminal
        - automation
        - developer-experience
        - tools
        - workflow
        - open-source
        - community
        - performance
        - ease-of-use
        - innovation
    validations:
      required: true

  - type: checkboxes
    id: avatar_consent
    attributes:
      label: Professional Attribution
      description: Avatar usage for professional attribution in testimonials and contributor profiles
      options:
        - label: I consent to using my profile avatar for testimonial display and contributor attribution
          required: true

  - type: checkboxes
    id: consent
    attributes:
      label: Collaboration Agreement
      description: Confirm your agreement for testimonial publication and collaboration invitation
      options:
        - label: I consent to having my testimonial featured on the X-CLI website with professional attribution
          required: true
        - label: I confirm this testimonial is truthful and based on my actual experience with X-CLI
          required: true
        - label: I understand I will receive a GitHub collaboration invitation with repository access
          required: true
        - label: I agree to contribute constructively to the project as a repository collaborator
          required: true

  - type: markdown
    attributes:
      value: |
        ---
        
        ### Professional Onboarding Process
        
        **Immediate Next Steps:**
        1. **Automated Processing** - System creates pull request with your testimonial and validates content
        2. **Publication** - Your testimonial goes live on our website within 10 minutes with full attribution
        3. **Collaboration Invitation** - You receive GitHub repository access with triage permissions
        4. **Professional Benefits** - Permanent backlink, portfolio enhancement, and networking opportunities
        
        **After Submission:**
        - Check your email for the GitHub collaboration invitation
        - Explore the codebase and contribution guidelines
        - Join technical discussions and start contributing improvements
        - Connect with other developers in the community
        
        **Questions?** Join our [Discord community](https://discord.com/channels/1315720379607679066/1315822328139223064) or participate in repository discussions.
        
        **Welcome to the X-CLI development community.**